version: '3.8'
services:
  db-auth-service:
    image: 'postgres:latest'
    container_name: 'db-auth-service'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth-service
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - minha-rede

  api:
    image: 'victojoao/auth-service:1.0'
    container_name: 'auth-service'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-auth-service:5432/auth-service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "9000:9000"
    depends_on:
      - db-auth-service
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge

volumes:
  db_data: